Repository sound-data/DEER-Prototypes-EnergyPlus, pull requests merged in 2024-04, with the labels that each got.

#44 Water heater template for SFm
  README.md
  prototypes/WaterHeaterModels/packagedHPWH_stratified_tank_conditioned.idf
  prototypes/WaterHeaterModels/root.pxt
  residential measures/SWXX000-00 Water Heater/.modelkit-config
  residential measures/SWXX000-00 Water Heater/SWXX000-00 Water Heater_SFm/cases/SFm_1_DXGF_Ex_WaterHeater.csv
  residential measures/SWXX000-00 Water Heater/SWXX000-00 Water Heater_SFm/climates.csv
  residential measures/SWXX000-00 Water Heater/SWXX000-00 Water Heater_SFm/cohorts.csv
  residential measures/SWXX000-00 Water Heater/SWXX000-00 Water Heater_SFm/hot water profile/SFm_minute_dhw_demand_fraction.csv
  residential measures/SWXX000-00 Water Heater/SWXX000-00 Water Heater_SFm/query.txt
  residential measures/SWXX000-00 Water Heater/rakefile.rb
  templates/energyplus/templates/water-heater.pxt
Labels: enhancement

#19 SWHC001-05 submission1
  querylibrary/query_benchmark.txt
  querylibrary/query_default.txt
  querylibrary/query_enduse.txt
  querylibrary/query_mfm_boiler_sizing.txt
  querylibrary/query_sfm_hvac_sizing_dxgf_dxhp.txt
  querylibrary/readme.md
  residential measures/SWHC001-05 Wall Furnace/.modelkit-config
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/cases/DMo&0&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/climates.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/cohorts.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/query.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/query_Wall Furnace.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_MFm_Ex/cases/MFm&0&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_MFm_Ex/climates.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_MFm_Ex/cohorts.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_MFm_Ex/query.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_MFm_Ex/query_Wall Furnace.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/cases/SFm&1&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/cases/SFm&2&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/climates.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/cohorts.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/query.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1975/query_Wall Furnace.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/cases/SFm&1&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/cases/SFm&2&rDXGF&Ex&SpaceHtg_eq__GasFurnace.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/climates.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/cohorts.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/query.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_SFm_1985/query_Wall Furnace.txt
  residential measures/SWHC001-05 Wall Furnace/SWHC001-Wall-Furnace_Measure_list.csv
  residential measures/SWHC001-05 Wall Furnace/SWHC001-Wall-Furnace_Measure_list.xlsx
  residential measures/SWHC001-05 Wall Furnace/global.pxv
  residential measures/SWHC001-05 Wall Furnace/rakefile.rb
  residential measures/SWHC001-05 Wall Furnace/readme.md
  scripts/data transformation/DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx
  scripts/data transformation/DMo.py
  scripts/data transformation/DMo_enduse.py
  scripts/data transformation/MFm.py
  scripts/data transformation/NumStor2.xlsx
  scripts/data transformation/SFm.py
  scripts/data transformation/insert_normunits.py
  scripts/result.py
Labels: New measure

#31 SWHC004 Space Heating Boiler (residential subset)
  prototypes/residential/MFm-1985-boiler/root_boiler.pxt
  prototypes/residential/MFm-1985-boiler/root_steam_boiler.pxt
  prototypes/residential/MFm-New-boiler/root_boiler_new.pxt
  prototypes/residential/MFm-New-boiler/root_steam_boiler_new.pxt
  residential measures/SWHC004-07 Space Heating Boiler/.modelkit-config
  residential measures/SWHC004-07 Space Heating Boiler/DEER_EnergyPlus_Modelkit_Measure_list_working.SWHC004-Res.xlsx
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/cases/MFm&0&rNCHW&Ex&SpaceHtg_eq__HotWaterBoiler.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/cases/MFm&0&rNCHW&Ex&SpaceHtg_eq__SteamBoiler.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/climates.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/cohorts.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/query.txt
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_Ex/query_boiler_sizing.txt
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/cases/MFm&0&rNCHW&New&SpaceHtg_eq__HotWaterBoiler.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/cases/MFm&0&rNCHW&New&SpaceHtg_eq__SteamBoiler.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/climates.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/cohorts.csv
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/query.txt
  residential measures/SWHC004-07 Space Heating Boiler/SWHC004-07 Space Heating Boiler_MFm_New/query_boiler_sizing.txt
  residential measures/SWHC004-07 Space Heating Boiler/global.pxv
  residential measures/SWHC004-07 Space Heating Boiler/rakefile.rb
  residential measures/SWHC004-07 Space Heating Boiler/readme.md
Labels: New measure

#32 Develop hydronic loop in residential MFm (rNCHW) (feature)
  prototypes/residential/MFm-1985-boiler/root_boiler.pxt
  prototypes/residential/MFm-1985-boiler/root_steam_boiler.pxt
  prototypes/residential/MFm-New-boiler/root_boiler_new.pxt
  prototypes/residential/MFm-New-boiler/root_steam_boiler_new.pxt
Labels: enhancement

#52 Fix code issues
  codes/T24_2025.csv
  codes/T24_2025_highriseres_hotel.csv
  codes/T24_2025_new.csv
Labels: bug
